[2025-01-31T04:45:09.601+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag1_v2.second_task scheduled__2022-02-26T00:00:00+00:00 [queued]>
[2025-01-31T04:45:09.614+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag1_v2.second_task scheduled__2022-02-26T00:00:00+00:00 [queued]>
[2025-01-31T04:45:09.614+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 6
[2025-01-31T04:45:09.632+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): second_task> on 2022-02-26 00:00:00+00:00
[2025-01-31T04:45:09.642+0000] {standard_task_runner.py:57} INFO - Started process 3222 to run task
[2025-01-31T04:45:09.648+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag1_v2', 'second_task', 'scheduled__2022-02-26T00:00:00+00:00', '--job-id', '826', '--raw', '--subdir', 'DAGS_FOLDER/dag_example.py', '--cfg-path', '/tmp/tmp21nygys9']
[2025-01-31T04:45:09.650+0000] {standard_task_runner.py:85} INFO - Job 826: Subtask second_task
[2025-01-31T04:45:09.776+0000] {task_command.py:415} INFO - Running <TaskInstance: dag1_v2.second_task scheduled__2022-02-26T00:00:00+00:00 [running]> on host f8bdfcb8bca5
[2025-01-31T04:45:09.949+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='anhtupham99' AIRFLOW_CTX_DAG_ID='dag1_v2' AIRFLOW_CTX_TASK_ID='second_task' AIRFLOW_CTX_EXECUTION_DATE='2022-02-26T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2022-02-26T00:00:00+00:00'
[2025-01-31T04:45:09.951+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-01-31T04:45:09.952+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'echo I am the second task, I run after the first task']
[2025-01-31T04:45:09.973+0000] {subprocess.py:86} INFO - Output:
[2025-01-31T04:45:09.976+0000] {subprocess.py:93} INFO - I am the second task, I run after the first task
[2025-01-31T04:45:09.977+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-01-31T04:45:10.023+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=dag1_v2, task_id=second_task, execution_date=20220226T000000, start_date=20250131T044509, end_date=20250131T044510
[2025-01-31T04:45:10.064+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-01-31T04:45:10.163+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
